# Created by react-native-pod
target 'Niot' do
  # We uncomment because we like dynamic frameworks witn working with swift projects
  use_frameworks!
  # Add new pods below this line
  target 'NiotTests' do
    inherit! :search_paths
    # Pods for testing
    # Add new pods below this line
  end
end
target 'Niot-tvOS' do
  # We uncomment because we like dynamic frameworks witn working with swift projects
  use_frameworks!
  target 'Niot-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end